[programs.localnet]
sc_sol = "4DzTzA5yGGX9bF7fpScPmRKLEMfxqaLUuECBsMbH1kEt"

[registry]
url = "https://api.devnet.solana.com"

[provider]
cluster = "devnet"
wallet = "/Users/mzk/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/"
